---
# tasks file for install-zookeeper



- name: transfer the zookeeper properties
  template:
    src: zookeeper.properties.j2
    dest: /home/ubuntu/kafka/config/zookeeper.properties
    owner: ubuntu
    group: ubuntu