---
# tasks file for install-zookeeper

- name: update the swapiness on the servers
  shell:
    sudo sysctl vm.swappiness=1
  
- name: download kafka package
  command: >-
     wget https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz

- name: untar kafka package
  command: >-
     tar -xvzf kafka_2.12-0.10.2.1.tgz

- name: remove the zip file
  command: >-
     rm -rf kafka_2.12-0.10.2.1.tgz

- name: remove pre-existing kafka directory
  command: >-
     rm -rf kafka
     
- name: rename kafka directory
  command: >-
     mv kafka_2.12-0.10.2.1 kafka

- name: change the owner of the kafka directory
  command: >-
     chown -R ubuntu:ubuntu /home/ubuntu/kafka
     
- name: create zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: 0644

- name: create zookeeper data directory
  command: >-
     mkdir -p /data/zookeeper

- name: create zookeeper data directory
  command: >-
     chown -R ubuntu:ubuntu /data/

- name: create the myid file
  copy:
    content: "{{ item.value.id }}"
    dest: /data/zookeeper/myid
    mode: 0664
  with_dict: 
       "{{ servers }}"
  when: ansible_hostname == item.key

- name: transfer the zookeeper properties
  template:
    src: zookeeper.properties.j2
    dest: /home/ubuntu/kafka/config/zookeeper.properties
    owner: ubuntu
    group: ubuntu