---
# tasks file for install-zookeeper

- name: update the swapiness on the servers
  command: >-
      sysctl vm.swappiness=1
  register: ls_output

- name: update the sysctl conf file
  command: >-
    echo 'vm.swappiness=1' | sudo tee --append /etc/sysctl.conf
  
- name: update the /etc/hosts file
  command: >-
     echo "172.31.0.6 kafka1
           172.31.0.6 zookeeper1
           172.31.1.6 kafka2
           172.31.1.6 zookeeper2
           172.31.2.6 kafka3
           172.31.2.6 zookeeper3" | sudo tee --append /etc/hosts

- name: download kafka package
  command: >-
     wget https://archive.apache.org/dist/kafka/0.10.2.1/kafka_2.12-0.10.2.1.tgz

- name: untar kafka package
  command: >-
     tar -xvzf kafka_2.12-0.10.2.1.tgz

- name: remove the zip file
  command: >-
     rm -rf kafka_2.12-0.10.2.1.tgz

- name: remove pre-existing kafka directory
  command: >-
     rm -rf kafka

- name: rename kafka directory
  command: >-
     mv kafka_2.12-0.10.2.1 kafka

- name: create zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    mode: 0644

- name: create zookeeper data directory
  command: >-
     mkdir -p /data/zookeeper

- name: create zookeeper data directory
  command: >-
     chown -R ubuntu:ubuntu /data/

- name: create the myid file
  copy:
    content: "{{ item.id }}"
    dest: /data/zookeeper/myid
    mode: 0664
  with_items: 
      - id: 1
        hostname: ip-172-31-0-6
      - id: 2
        hostname: ip-172-31-1-6
      - id: 3
        hostname: ip-172-31-2-6
  when: ansible_hostname == item.hostname      