---
# tasks file for net-tools
- name: Install transport https
  package:
    update_cache: yes
    name: apt-transport-https
    state: latest

- name: Instal ca-certificates
  package:
    update_cache: yes  
    name: ca-certificates
    state: latest

- name: install curl
  package:
    update_cache: yes  
    name: curl
    state: latest

- name: install wget
  package:
    update_cache: yes  
    name: wget
    state: latest

- name: install zip
  package: 
    update_cache: yes  
    name: zip
    state: latest

- name: install net-tools
  package:
    update_cache: yes  
    name: net-tools
    state: latest

- name: install nano
  package:
    update_cache: yes  
    name: nano
    state: present

- name: install tar
  package:
    update_cache: yes  
    name: tar
    state: latest

- name: install net-cat
  package:
    update_cache: yes  
    name: netcat
    state: latest

- name: install openjdk-8-jdk
  package:
    update_cache: yes  
    name: openjdk-8-jdk
    state: latest    
...